### PR TITLE
Sciquery

### PR DESCRIPTION
**Pull request by mtaghiza**
Adding SciQuery functionality.

### CODE REVIEW

**Review by glemson — COMMENTED** [review]
General comment is that I think it would be good to introduce some classes, maybe one for SciQuery and one for RDBComputeDomain, against which one can call functions.
Could come with a bunch of initialization codes like SciQuery initializinng the RDBComputeDOmain-s and their dbcontexts the user has access to, the fileservice instance (generally there will be only one), setting default target volumes etc.

**Review by glemson — COMMENTED** [review]
Manu, it would be good to turn this into a proper PR soon.
Leaving it as Draft so long means the final reviewers are getting a LOT of work to do.

**Comment by mtaghiza** [comment]
@glemson  Note that the amount of work is the same as before, as there are no other modules intended to be modified for this PR. Last commits are only minor updates on previous code in the same module.

**Review by shandy79 — APPROVED** [review]
I was able to successfully run the short and long demo notebooks from Getting Started/AAS2023/SciQuery  in the Astronomy image on prod.

**Review by glemson — APPROVED** [review]
go ahead.

**Pull request merged**
